### PR TITLE
added mysqldump to my.cnf

### PR DESCRIPTION
**Pull request by isehgu**
@cbautista1002 please review and merge.

### CODE REVIEW

**Comment by cbautista1002** [comment]
This is the same change you made in your AWS instance to get it to work?

**Comment by isehgu** [comment]
Copy/paste the same content as my change into aws, including comments. Mysqldump works.

```bash-4.3# vi /etc/mysql/my.cnf
bash-4.3# mysqldump -u root map_db > test.sql
bash-4.3# ls
MAP_Regression_Results    bdt_map_circleci.py       bdt_map_testenv_setup.py  log.log                   test.sql
bdt                       bdt_map_setup.sh          glowing-configurator      robotframework
```

**Comment by isehgu** [comment]
my.cnf
```
bash-4.3# cat /etc/mysql/my.cnf
[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
user=mysql
# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0

# Make mysql server listen to more than localhost so that we can connect from outside of our container
bind-address = 0.0.0.0

[mysqld_safe]
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
socket=/var/lib/mysql/mysql.sock

[mysql]
socket=/var/lib/mysql/mysql.sock

#When reading the configuration file, the mysql command line client only reads 
#configuration directives found in the [client] and [mysql] sections, 
#while mysqldump only uses configuration #directives found in the [client] and 
#[mysqldump] sections.
#http://dba.stackexchange.com/questions/46296/mysql-works-mysqldump-doesnt
[mysqldump]
socket=/var/lib/mysql/mysql.sock
bash-4.3# 
```

**Comment by cbautista1002** [comment]
Awesome!

**Pull request merged**
