### PR TITLE
Initial docker-compose file

### PR DESCRIPTION
**Pull request by cbautista1002**
docker-compose file to handle multiple docker containers.

### CODE REVIEW

**Comment by cbautista1002** [comment]
Tested in AWS with dockerfiles and setup before Alpine and Circle-ci additions, since new architecture needs some cleanup.
```
core@ip-192-168-254-209 ~/cb_compose_test $ ~/docker-compose up -d
Recreating cbcomposetest_ftpdatavol_1...
Recreating cbcomposetest_mysqldatavol_1...
Recreating cbcomposetest_mapapp_1...
Recreating cbcomposetest_ftpapp_1...

core@ip-192-168-254-209 ~/cb_compose_test $ ~/docker-compose ps   
              Name                             Command                             State                              Ports               
-----------------------------------------------------------------------------------------------------------------------------------------
cbcomposetest_ftpapp_1             /bin/sh -c /start.sh               Up                                 0.0.0.0:19921->21/tcp            
cbcomposetest_ftpdatavol_1         /bin/sh -c /bin/sh                 Exit 0                                                              
cbcomposetest_mapapp_1             supervisord -n                     Up                                 0.0.0.0:49157->18900/tcp,        
                                                                                                         0.0.0.0:49153->18901/tcp,        
                                                                                                         0.0.0.0:49154->22/tcp,           
                                                                                                         0.0.0.0:49155->3306/tcp,         
                                                                                                         0.0.0.0:49156->80/tcp            
cbcomposetest_mysqldatavol_1       /bin/sh -c /bin/sh                 Exit 0                                                              

core@ip-192-168-254-209 ~/cb_compose_test $ ssh -p 49154 root@localhost
The authenticity of host '[localhost]:49154 ([127.0.0.1]:49154)' can't be established.
RSA key fingerprint is c2:6d:2c:d4:ac:6b:b4:56:d8:9f:2d:df:d7:8b:fc:a9.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[localhost]:49154' (RSA) to the list of known hosts.
root@localhost's password: 
-bash-4.1# exit
logout
Connection to localhost closed.
core@ip-192-168-254-209 ~/cb_compose_test $
```

**Comment by cbautista1002** [comment]
@jumanjiman please review and merge.

**Comment by jumanjiman** [comment]
> please review and merge.

on it. 

how very cool!

**Comment by jumanjiman** [comment]
merged!

**Comment by cbautista1002** [comment]
Thanks! I'm testing with the new arch now.

**Pull request merged**
