### PR TITLE
wip (no merge yet): mysql and pr images

### PR DESCRIPTION
**Pull request by jumanjiman**
* circle now publishes test images for each pull request
* wip (no merge): setup mysqld during docker build

### CODE REVIEW

**Comment by jumanjiman** [comment]
@cbautista1002 Can you test this image?

    docker pull quay.io/iseexchange/tacstack:jumanjiman_pull_33

**Comment by cbautista1002** [comment]
Yep!

**Comment by cbautista1002** [comment]
MySQL is still not starting. Its not picking up the correct socket.

```
$ docker run -d -p 20022:22 -p 20080:80 -p 20006:3306 --name testing_pull_33 --volumes-from adoring_lumiere quay.io/iseexchange/tacstack:jumanjiman_pull_33

$ ssh -p 20022 root@localhost

9e1f49a3eed6:~# mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

9e1f49a3eed6:~# ps -ef
PID   USER     TIME   COMMAND
    1 root       0:00 {supervisord} /usr/bin/python /usr/bin/supervisord -n
   11 root       0:00 /usr/sbin/httpd -DFOREGROUND
   12 root       0:00 /usr/sbin/sshd -D
  187 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  188 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  189 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  190 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  191 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  714 root       0:00 sshd: root@pts/0
  716 root       0:00 -ash
  718 root       0:00 ps -ef

9e1f49a3eed6:~# service mysql start
 * WARNING: mysql is already starting

9e1f49a3eed6:~# ps -ef
PID   USER     TIME   COMMAND
    1 root       0:00 {supervisord} /usr/bin/python /usr/bin/supervisord -n
   11 root       0:00 /usr/sbin/httpd -DFOREGROUND
   12 root       0:00 /usr/sbin/sshd -D
  187 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  188 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  189 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  190 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  191 apache     0:00 /usr/sbin/httpd -DFOREGROUND
  714 root       0:00 sshd: root@pts/0
  716 root       0:00 -ash
  720 root       0:00 ps -ef

9e1f49a3eed6:~# service mysqld start
 * service: service `mysqld' does not exist
```

**Comment by cbautista1002** [comment]
I also tried it without a data volume and same error. Except this time at least mysql.sock exists in /var/lib/mysql where it did not with the data volume.

```
$ docker run -d -p 20122:22 -p 20180:80 -p 20106:3306 --name testing_pull_33_2 quay.io/iseexchange/tacstack:jumanjiman_pull_33

$ ssh -p 20122 root@localhost

6cc17813ba07:~# mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
6cc17813ba07:~# ls /var/lib/mysql
ib_logfile0         ib_logfile1         ibdata1             mysql               mysql.sock        performance_schema  test

6cc17813ba07:~# mysql socket="/var/lib/mysql/mysql.sock"
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by jumanjiman** [comment]
> Its not picking up the correct socket.

i wondered about that.
http://oneye-project.org/ simply renamed your `my.cnf` (which specifies `/var/lib/mysql...` socket)

i will change the various configs to use `/var/run/mysql...` socket so we don't have to specify `--socket` on cli.

in meantime, break the habit of using `service mysqld start`. you need to use `supervisorctl [start|stop|restart] mysql`. supervisord is your init system.

**Pull request merged**
