### PR TITLE
Add robot envvar and .proxy

### PR DESCRIPTION
**Pull request by cbautista1002**
- Moved proxy environment variables into its own file (.proxy) so its not automatically sourced. You'll have to source this manually if you need it (if you're within ISE's walls)
- Added `PYTHONPATH=/home/robotframework` to `docker-compose-common.yml`
- Removed unnecessary 3 second delay from supervisord's map start

### CODE REVIEW

**Comment by cbautista1002** [comment]
@jwasserzug Please review and merge. I tested this on td-tac01 using `quay.io/iseexchange/tacstack:cbautista1002_pull_55`.

**Comment by jwasserzug** [comment]
`Added PYTHONPATH=/home/robotframework to docker-compose-common.yml`

Does this effect the python path for other uses other than importing modules from robotframework?

**Comment by cbautista1002** [comment]
I tested it by importing built in and installed python modules (os, etcd), so the default python path is not affected. If there are directories you need in your path, they would have to be added either through the docker-compose file or a .bashrc file.

In our case I think this works. Are there any other paths you're concerned about?

**Comment by jwasserzug** [comment]
All seems good.

Merged!

**Pull request merged**
