### PR TITLE
wip: Add a new build script to help with circleci integration

### PR DESCRIPTION
**Pull request by cbautista1002**

### CODE REVIEW

**Comment by cbautista1002** [comment]
circleci is for some reason failing the build. I manually updated quay with a locally built tacstack image (in AWS).

**Comment by cbautista1002** [comment]
@jwasserzug  Please review and merge.

**Comment by cbautista1002** [comment]
Tested via https://circleci.com/gh/ISEexchange/bdt/42

**Comment by jwasserzug** [comment]
looks good!

**Comment by jwasserzug** [comment]
Merged!

**Pull request merged**
