### PR TITLE
Add detailed instructions for MAP

### PR DESCRIPTION
**Pull request by cbautista1002**
I've added detailed instructions for setting up MAP after the containers have been constructed.

### CODE REVIEW

**Comment by cbautista1002** [comment]
Waiting for CircleCI to complete.

**Comment by cbautista1002** [comment]
@jwasserzug @isehgu Please review and merge.

**Comment by jwasserzug** [comment]
Sweet

**Comment by jwasserzug** [comment]
Merged!

**Comment by cbautista1002** [comment]
Thanks!

**Pull request merged**
